### ISSUE TITLE
Coyote jump issue

### ISSUE THREAD

**Issue by kartofelek007** [uheartbeast/Heart-Platformer-Godot-4#1]
It seems to me that the coyote jump is much larger than the normal jump. I did some testing for myself using print() and it comes out that line 58 for player.gd lets go of the condition and then continues to pass holding the key up.
Suggestion for change:
adding an additional variable for example coyote_jump_start. When you start timer - you set it to true. After line 58 you set it to false?

```
	if just_left_ledge:
		coyote_jump_timer.start()
		coyote_jump_start = false
```

```
	if is_on_floor() or (coyote_jump_timer.time_left > 0.0 and coyote_jump_start):
		if Input.is_action_pressed("jump"):
			velocity.y = movement_data.jump_velocity
			coyote_jump_start = false
```
I'm not good at godot. Maybe you know better methods.

**Comment by uheartbeast** [comment]
Hey! thanks for bringing this up. I addressed this in the most recent commit (and future video).

Your solution works well. I ended up just calling stop() on the timer after executing a coyote jump for my solution.
